on: [push]

jobs:
  run_docker:
    runs-on: ubuntu-latest
    name: start docker container
    outputs:
      output-from-docker: ${{ steps.docker.outputs.result }}

    steps:
  
      # get content of Repository into the current workingdirectory
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: docker action
        uses: ./ # Uses an action in the root directory
        id: docker

      # Use the output from the `hello` step
      - name: Display the output
        run: echo "The result was ${{ steps.docker.outputs.result }}"
        
  evaluate:
    needs: run_docker
    runs-on: ubuntu-latest
    steps:
        # get content of Repository into the current workingdirectory
      - name: Checkout
        uses: actions/checkout@v3
        
        # check if the result of the docker execution is correct
      - name: run eval-Script
        run: bash ./eval.sh
        env:
          ENV_RESULT: ${{ needs.run_docker.outputs.output-from-docker }}
